name = "gm-assistant-bot-web"
main = "src/worker.ts"
compatibility_date = "2025-12-11"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"

[observability]
enabled = true
