name = "gm-assistant-bot-web"
main = "./dist/index.js"
compatibility_date = "2025-12-12"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"

[observability]
enabled = true
